### ISSUE TITLE
Optionally consider footnote definition those without ^

### ISSUE THREAD

**Issue by swfsql** [ancap-ch/from-en#1321]
User @gn-ahmad reported that putting that character would mess the writing for Persian/Farsi.
So it's better to also consider those as footnote definitions.

**Comment by gn-ahmad** [comment]
Hi @swfsql 
You choose me as the main proofreader and I express my gratitude for this. persian language translators says that persian is not confirmed in the main project and you are responsible of that,  so if it is possible, confirm and apply me as proofreader in the project so as we can develop persian and persian translators begin working, I wish to be a good assistant for you and the main project in the best way.

**Comment by gn-ahmad** [comment]
@swfsql  And almost half of the book is translated so you can combine it with the main project. 
And my request from you is to apply me as the proofreader or check and confirm my incidental project.
https://github.com/gn-ahmad/from-en/tree/utopian/fa

**Comment by swfsql** [comment]
Moved to https://github.com/swfsql/genpdf/issues/23
