### ISSUE TITLE
I have chosen several files and look forward to get the translation permission

### ISSUE THREAD

**Issue by hushuilan** [ancap-ch/from-en#1671]
Hi! I am interested in some files and I hope to contribute my translation. I will work hard to translate these words to Simplified Chinese . I have modified the reame.md file under the ZH-CN folder.  I wonder if I have the privilege of obtaining your translation permission. Please merge my PR(#1670), thank you very much!

**Comment by swfsql** [comment]
Since you got in touch with rosatravels, I'll be closing the issue 👍
