### ISSUE TITLE
There are so few translation activities in the last two days

### ISSUE THREAD

**Issue by hushuilan** [ancap-ch/from-en#2187]
There are so few translation activities in the last two days. The progress of merging PR is also relatively slow. Is the translation of the project being upgraded recently?

**Comment by swfsql** [comment]
Hi hushuilan, almost all of the contributions comes fro the utopian platform, and they are working towards making it better after some problems that occurred. It may be the case that this repository will remain considered as not qualified to be listed in their own platform.

**Comment by swfsql** [comment]
So I'll be closing now as this is external to this project.
