### ISSUE TITLE
Translation English to Romanian

### ISSUE THREAD

**Issue by AdyWasHere** [ancap-ch/from-en#256]
Hi there I am a Romanian member from Utopian, I wanted to ask you if I can translate your project from English to Romanian. If you want, please create the EN-RO folder inside your translations and I'll start transalting.

Sorry for posting this as a new issue but this is the only way I found to contact someone on github.

Thanks in advance.

**Comment by swfsql** [comment]
Hi! sure, no problem. And don't worry, opening an issue is fine :)

**Comment by swfsql** [comment]
It has been created: https://github.com/ancap-ch/from-en/tree/utopian/ro
