### ISSUE TITLE
Localization/Translation to Filipino

### ISSUE THREAD

**Issue by Cyyy1998** [ancap-ch/from-en#682]
Good day i want to contribute in translation

**Comment by BelovedAquila** [comment]
welcome friend,you can join in the translation projects ,but to start,
Please friend, 
- Join https://groups.google.com/forum/#!forum/rchain
- Accept https://github.com/rchain/Members/invitations
- Send your emailaddress + github name to ops@rchain.coop

**Comment by rfece143** [comment]
hello...can i join you in  contributing Filipino translation for this project..

**Comment by BelovedAquila** [comment]
@rfece143 of course you can join in, follow the directions given to @Cyyy1998 above to get started please.

**Comment by Cyyy1998** [comment]
Is it true that it have membership fee?

**Comment by BelovedAquila** [comment]
@Cyyy1998 pardon me, your question isn't clear.
Is it true that what has membership fees please?

**Comment by Cyyy1998** [comment]
@BelovedAquila  when creating account for rchain

**Comment by Cyyy1998** [comment]
![image](https://user-images.githubusercontent.com/36368860/36348539-b50c1c90-14ac-11e8-90e5-dcd48324380f.png)

What is the meaning of this?

**Comment by BelovedAquila** [comment]
@Cyyy1998 so sorry that inconvenience, please send your complaint to @lapin7 via lapin7@gmail.com.

**Comment by lapin7** [comment]
Please move this discussion to and issue in [Bounties](https://github.com/rchain/bounties/issues/358)

**Comment by swfsql** [comment]
@Cyyy1998 I own this repository (ancap.ch/from-en) and I'm sorry for taking this long to reply.
Could you please send a message to me on discord? (thi#3282) 

I have no idea who belovedaquila nor lapin7 are, and theres nothing of this fee nonsense. I'll be removing and reporting them.

**Comment by rfece143** [comment]
sir swfsql ....thanks for the reply...can i still join sir..?

**Comment by Cyyy1998** [comment]
Accept my request sir . I cant send message to you.

**Comment by lapin7** [comment]
You can send a message to ops@rchain.coop

--
Cheers,
HJ

**Comment by swfsql** [comment]
Hello again Cyyy and also, rfece,
I'm sorry for the delay in responding.

Due to the high frequency of people using bots to translate text, the collaborators were struggling for proofreading since this wasn't viewed as a required "work that had to be recompensated" by utopian platform.

I thank you for trying to find the best way to contribute, and I'm sorry I took so long to reply.
So.. since this project is not involved with utopian anymore, then I'll be closing this issue for now.
