### ISSUE TITLE
Move to Github

### ISSUE THREAD

**Issue by swfsql** [ancap-ch/from-en#983]
It is planned to eventually move to Github, so more texts can be added and the languages remain with a large time window to do translations and proofreading free of cost.

It's easier to organize insertions, and to have a coherent team of people working on the same book/essay project.

But more tools will be needed to facilitate contributions proofreading, and the workflow must be as simple as possible. With an organized team workflow (when you know what text you're working on, and others also know that), very feel conflict cases will arise.

**Comment by ackseriam** [comment]
Hello @swfsql , please, if you can take me into account for contributions, I would appreciate it. Please check the contribution I made here 4566d3a  . Here is my pull request #925.

**Comment by swfsql** [comment]
Moved to https://github.com/swfsql/genpdf/issues/29
